#!/bin/bash

set -e

"${@}" 3> >(
    DATAPATH=~/.local/share/equihash
    read n k
    [[ -d "$DATAPATH" ]] || mkdir -p "$DATAPATH"
    [[ -f "$DATAPATH"/$n-$k ]] &&
        txt="This will take approximately $(awk '{sum+=$1; ++n} END {printf "%.4f\n", sum/n}' <"$DATAPATH"/$n-$k) seconds" ||
        txt="Never saw this difficulty ($n,$k) before, unknown how long it will take"

    # could also be pinentry (SETDESC $txt\nMESSSAGE\n wait... QUIT\n)
    # or some dbus stuff for popup notifications
    # or even conky or other stuff is possible whatever is prefered
    zenity --progress --pulsate --no-cancel --title "Equihash challenge solving..." --text "$txt" &
    pid=$!

    cat >>"$DATAPATH"/$n-$k
    echo >>"$DATAPATH"/$n-$k
    kill $pid 2>/dev/null
)
